// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[page]" | "/[locale]/account/[[...section]]" | "/[locale]/blog/[slug]" | "/[locale]/order/[orderNumber]" | "/[locale]/product/[slug]" | "/[locale]/shop/[[...category]]" | "/admin/[[...section]]"
type AppRouteHandlerRoutes = "/api/[...path]" | "/api/admin-upload" | "/api/admin/[...path]" | "/api/auth/[...nextauth]" | "/api/quote-attachment" | "/api/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/[page]": { "locale": string; "page": string; }
  "/[locale]/account/[[...section]]": { "locale": string; "section"?: string[]; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/order/[orderNumber]": { "locale": string; "orderNumber": string; }
  "/[locale]/product/[slug]": { "locale": string; "slug": string; }
  "/[locale]/shop/[[...category]]": { "locale": string; "category"?: string[]; }
  "/admin": {}
  "/admin/[[...section]]": { "section"?: string[]; }
  "/api/[...path]": { "path": string[]; }
  "/api/admin-upload": {}
  "/api/admin/[...path]": { "path": string[]; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/quote-attachment": {}
  "/api/upload": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
